// Hexdump.js 0.1.2
// (c) 2011 Dustin Willis Webber
// Hexdump is freely distributable under the MIT license.
// For all details and documentation:
// http://github.com/mephux/hexdump.js
var Hexdump;
Hexdump=function(){function f(c,b){var a=this;a.hexdump=[];a.hex=!1;a.options={container:b.container||"",width:b.width||16,byteGrouping:b.byteGrouping||0,ascii:b.ascii,lineNumber:b.lineNumber,endian:b.endian||"big",html:b.html,base:b.base||"hexadecimal",nonPrintable:b.nonPrintable||".",style:{lineNumberLeft:b.style.lineNumberLeft||"",lineNumberRight:b.style.lineNumberRight||":",stringLeft:b.style.stringLeft||"|",stringRight:b.style.stringRight||"|",hexLeft:b.style.hexLeft||"",hexRight:b.style.hexRight||"",
hexNull:b.style.hexNull||".",stringNull:b.style.stringNull||" "}};"hex"==a.options.base?a.hex=!0:"hexadecimal"==a.options.base&&(a.hex=!0);b=a.options.lineNumber;if("undefined"==typeof b||null==b)a.options.lineNumber=!0;b=a.options.ascii;if("undefined"==typeof b||null==b)a.options.ascii=!1;b=a.options.html;if("undefined"==typeof b||null==b)a.options.html=!0;"little"!=a.endian&&(a.endian="big");a.options.byteGrouping>c.length&&(a.options.byteGrouping=c.length);a.options.byteGrouping--;a.options.width>
c.length&&(a.options.width=c.length);a.padding={hex:4,dec:5,bin:8};switch(a.options.base){case "hexadecimal":case "hex":case 16:a.setNullPadding(a.padding.hex);a.baseConvert=function(b){for(;0<b.length;)return a.addPadding(b[0].charCodeAt(0).toString(16),a.padding.hex)};break;case "decimal":case "dec":case 10:a.setNullPadding(a.padding.dec);a.baseConvert=function(b){for(;0<b.length;)return a.addPadding(b[0].charCodeAt(0),a.padding.dec)};break;case "binary":case "bin":case 2:a.setNullPadding(a.padding.bin);
a.baseConvert=function(b){for(;0<b.length;){b=b[0].charCodeAt(0);for(var c="",d=0;8>d;d++)c=b%2+c,b=Math.floor(b/2);return a.addPadding(c,a.padding.bin)}};break;default:a.options.base="hex",a.hex=!0,a.setNullPadding(a.padding.hex),a.baseConvert=function(b){for(;0<b.length;)return a.addPadding(b[0].charCodeAt(0).toString(16),a.padding.hex)}}a.data=c.match(new RegExp(".{1,"+this.options.width+"}","g"));a.nullCount=a.options.width-a.data[a.data.length-1].length;a.hexCounter=0;for(c=a.stringCounter=0;c<
a.data.length;c++)b=a.process(a.data[c]),a.hexdump.push({data:b.data,string:b.string,length:a.data[c].length,missing:a.options.width-a.data[c].length});a.dump()}f.prototype.dump=function(){this.output="";for(var c=0;c<this.hexdump.length;c++){if(this.options.lineNumber){var b="";b+=this.options.style.lineNumberLeft;for(var a=c*this.options.width,d=8-a.toString().length,e=0;e<d;e++)b+="0";b+=a;b+=this.options.style.lineNumberRight+" ";this.output=this.options.html?this.output+('<span id="line-number">'+
b+"</span>"):this.output+b}b=0;this.output+=this.options.style.hexLeft;for(a=0;a<this.hexdump[c].data.length;a++)b==this.options.byteGrouping?(this.output=a==this.hexdump[c].data.length-1?this.output+this.hexdump[c].data[a]:this.output+(this.hexdump[c].data[a]+" "),b=0):(this.output+=this.hexdump[c].data[a],b++);this.output+=this.options.style.hexRight;this.appendString(this.hexdump[c]);this.output+="\n"}document.getElementById(this.options.container).innerHTML=this.output};f.prototype.appendString=
function(c){this.output+=" "+this.options.style.stringLeft;this.output+=c.string;this.output+=this.options.style.stringRight};f.prototype.splitNulls=function(c){var b=[],a="";if(c&&2<c.length)for(var d=0;d<c.length;d++)0==(d+1)%2?(a+=c[d].toString(),b.push(a),a=""):a+=c[d].toString();return b};f.prototype.process=function(c){for(var b=[],a=[],d=0;d<c.length;d++){if(this.options.html){var e=this.baseConvert(c[d]);if(this.hex){e=this.splitNulls(e);for(var f=0;f<e.length;f++)a.push('<span data-hex-id="'+
this.hexCounter+'">'+e[f]+"</span>")}else a.push('<span data-hex-id="'+this.hexCounter+'">'+e+"</span>");b.push('<span data-string-id="'+this.hexCounter+'">'+this.checkForNonPrintable(c[d])+"</span>")}else{e=this.baseConvert(c[d]);if(this.hex)for(e=this.splitNulls(e),f=0;f<e.length;f++)a.push(e[f]);else a.push(e);b.push(this.checkForNonPrintable(c[d]))}this.hexCounter++}d=this.hex?2*this.options.width:this.options.width;if(a.length<d)for(c=d-a.length,d=0;d<c;d++)a.push(this.options.html?'<span data-hex-null="true">'+
this.options.style.hexNull+"</span>":this.options.style.hexNull);if(b.length<this.options.width)for(c=this.options.width-b.length,d=0;d<c;d++)b.push(this.options.html?'<span data-string-null="true">'+this.options.style.stringNull+"</span>":this.options.style.stringNull);return{data:a,string:b.join("")}};f.prototype.setNullPadding=function(c){var b=this.options.style.hexNull[0];this.options.style.hexNull="";this.hex&&(c/=2);for(var a=0;a<c;a++)this.options.style.hexNull+=b};f.prototype.addPadding=
function(c,b){for(var a=c.toString().length,d="",e=0;e<b-a;e++)d+="0";return"big"==this.options.endian?d+c:c+d};f.prototype.checkForNonPrintable=function(c){var b=c.charCodeAt(0).toString(16);return 9==b?".":127==b?".":2<b.length&&this.options.ascii?".":c};return f}();
